services:
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: react_app
        volumes:
          - app_client:/app
        ports:
          - 3000:3000
        depends_on:
          - backend

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: api_server
        volumes:
          - app_server:/var/www/html
        ports:
          - 80:80
        depends_on:
          - mysql
        networks:
            - app_network
    
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Root@123
            MYSQL_DATABASE: todo
            # MYSQL_USER: root
            # MYSQL_PASSWORD: Root@123
        ports:
            - 3307:3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
        
volumes:
    db_data:
    app_server:
    app_client:
